### ISSUE TITLE
Switching branches before selecting a subheader gives an error

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/redoc#24]
Steps to reproduce:

1. Navigate to the root (i.e. /) and do not select a subsection
2. Select a different branch from the dropdown
3. Observe that "Requested document not found for this version." is shown and the url contains "undefined"

Once you select a subsection, everything works as expected.

A failing acceptance test is included in PR

**Comment by mikemurray** [comment]
This should be fixed now
