### ISSUE TITLE
TOC Admin UI

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/redoc#3]
Insert, delete, reorder TOC from admin UI.
- add accounts, accounts-base
- add sortable, position property to TOC (or just use array order?)
- add discrete login link to docs
- add default admin user
- do not use "/admin" or anthing so obvious, so allow for docs "admin",.suggest "redoc/admin"
- visibility / publish / unpublish
- flushDocCache / refresh element

**Comment by marceloschmidt** [comment]
I'm working on building the TOC from the Github structure. This way, adding or removing an item would be as simple as making a PR to the repository. Ordering would be done by numbers in front of Directories or Files (01. Introduction; 02. Installing; 03. Configuring; etc.). If numbers are not found, it would use the alphabetical order. TOC items would remove the numbering in front of directory names to make UI better. Also, each directory may contain a README.md, which would be the link for the main item. 
I thought about making this an option, so you could select if you're using github structure or redoc.json, or initRepoData.
Would this interest you on a PR?

**Comment by aaronjudd** [comment]
I thought about this as well,  but was thinking more that we could use GitHub search for a repo to find all .md files and create a TOC index from them. I'd add to the `tocData` a `visibility` boolean per document.  I'm not sure about relying on a naming convention though, that might be hard to enforce if you have a lot of people contributing, changing docs.  It'd be a pretty simple UI to create a drag and drop navbar for positioning.. (we'd could go ahead and add a `position` to sort by now though).

**Comment by aaronjudd** [comment]
@mikemurray so the admin is now at: http://localhost:3000/redoc, right?
