### ISSUE TITLE
Broken link in email search results

### ISSUE THREAD

**Issue by willopez** [reactioncommerce/redoc#89]
Search the docs using the keyword 'email' the search results will include an item titled: "An Introduction to Architecture: Alerts, Notifications & Emails" which leads to a 404 :(

**Comment by machikoyasuda** [comment]
The search function will highlight the search term with a `<span>`, and will also add that to URLs:

<img width="1352" alt="screen shot 2018-01-26 at 2 35 23 pm" src="https://user-images.githubusercontent.com/3673236/35463587-44b45196-02a6-11e8-826b-09ef39ff51ec.png">
<img width="1024" alt="screen shot 2018-01-26 at 2 35 35 pm" src="https://user-images.githubusercontent.com/3673236/35463588-44d2d17a-02a6-11e8-913b-ba3d865c52c0.png">

**Comment by brent-hoover** [comment]
@machikoyasuda Generally good practice with duplicates is to keep the older ticket so that we have the true age of the issue.

**Comment by machikoyasuda** [comment]
Closing duplicate
