### ISSUE TITLE
header template method

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/redoc#9]
a header method to inject a remote header template and data to be rendered locally. This should be possible with [DDP.connect](http://docs.meteor.com/#/full/ddp_connect) . The goal would be that Meteor sites could have a continuous flow when integrated in another Meteor site, and `redoc` itself wouldn't need customization.

**Comment by mikemurray** [comment]
This is probably not needed anymore since the header can be configured via `settings.json`

**Comment by aaronjudd** [comment]
agreed, closing.
